# docker-compose.yml

services:
  backend:
    build: backend
    image: translator-backend:latest     
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
    networks:
      - project_network

  frontend:
    build: frontend
    image: translator-frontend:latest
    ports:
      - "8501:8501"
    volumes:
      - ./frontend:/app/frontend
    depends_on: 
    - backend
    networks:
      - project_network

networks:
  project_network: